%%Code that gives a user interface with buttons to calculate all kinds of
%%parameters 
% - Possible parameters are: 
% - single channel: mean firing rate (mfr), mean bursting 
% rate (mbr), mean burst duration (mbd), mean inter burst interval (ibi), mean percentage of
%random spikes (prs)
% - network level: network burst rate (nbr), duration of network bursts
%(dnb), inter burst interval of the network bursts (ibinb)across all wells 
%of one experiment and put them together in one file.
%ELINE

d = dialog('Position',[400 400 400 200],'Name','What do you want to calculate');
   
        txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[10 150 210 40],...
           'String','Select a single channel parameter you want to calculate'); 


      popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[70 140 100 20],...
           'String',{'MFR';'MBR';'MBD';'IBI';'PRS'},...
           'Callback',@popup_callback);
       
         txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[10 90 210 40],...
           'String','Select a network parameter you want to calculate'); 


      popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[70 80 100 20],...
           'String',{'NBR';'DNB';'IBINB'},...
           'Callback',@popup_callback);


        btn = uicontrol('Parent',d,...
           'Position',[200 139 160 25],...
           'String','ALL single channel parameters',...
           'Callback', 'CalculateMeans');

        btn = uicontrol('Parent',d,...
           'Position',[200 79 160 25],...
           'String','ALL network parameters',...
           'Callback', 'Calculatenetworkmeans');
  
        btn = uicontrol('Parent',d,...
           'Position',[150 20 70 25],...
           'String','Close',...
           'Callback','delete(gcf)');



%% ALTERNATIVE CODE 

% clear all 
% close all

% choice = 0;
% while choice ~=3
    
    % switch choice
       % case 1
            %CalculateMeans;
       % case 2
            %Calculatenetworkmeans;
       %%case 3
            %clf;
   % end
 % choice = menu ('What do you want to calculate', 'calculate single channel parameters', ...
    % 'calculate networkmeans', 'quit');
% end 